// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/docker/stacks/pkg/store (interfaces: ResourcesClient)

package mocks

import (
	context "context"
	api "github.com/docker/swarmkit/api"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	reflect "reflect"
)

// MockResourcesClient is a mock of ResourcesClient interface
type MockResourcesClient struct {
	ctrl     *gomock.Controller
	recorder *MockResourcesClientMockRecorder
}

// MockResourcesClientMockRecorder is the mock recorder for MockResourcesClient
type MockResourcesClientMockRecorder struct {
	mock *MockResourcesClient
}

// NewMockResourcesClient creates a new mock instance
func NewMockResourcesClient(ctrl *gomock.Controller) *MockResourcesClient {
	mock := &MockResourcesClient{ctrl: ctrl}
	mock.recorder = &MockResourcesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockResourcesClient) EXPECT() *MockResourcesClientMockRecorder {
	return _m.recorder
}

// CreateExtension mocks base method
func (_m *MockResourcesClient) CreateExtension(_param0 context.Context, _param1 *api.CreateExtensionRequest, _param2 ...grpc.CallOption) (*api.CreateExtensionResponse, error) {
	_s := []interface{}{_param0, _param1}
	for _, _x := range _param2 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "CreateExtension", _s...)
	ret0, _ := ret[0].(*api.CreateExtensionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExtension indicates an expected call of CreateExtension
func (_mr *MockResourcesClientMockRecorder) CreateExtension(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0, arg1}, arg2...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CreateExtension", reflect.TypeOf((*MockResourcesClient)(nil).CreateExtension), _s...)
}

// CreateResource mocks base method
func (_m *MockResourcesClient) CreateResource(_param0 context.Context, _param1 *api.CreateResourceRequest, _param2 ...grpc.CallOption) (*api.CreateResourceResponse, error) {
	_s := []interface{}{_param0, _param1}
	for _, _x := range _param2 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "CreateResource", _s...)
	ret0, _ := ret[0].(*api.CreateResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResource indicates an expected call of CreateResource
func (_mr *MockResourcesClientMockRecorder) CreateResource(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0, arg1}, arg2...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CreateResource", reflect.TypeOf((*MockResourcesClient)(nil).CreateResource), _s...)
}

// GetResource mocks base method
func (_m *MockResourcesClient) GetResource(_param0 context.Context, _param1 *api.GetResourceRequest, _param2 ...grpc.CallOption) (*api.GetResourceResponse, error) {
	_s := []interface{}{_param0, _param1}
	for _, _x := range _param2 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "GetResource", _s...)
	ret0, _ := ret[0].(*api.GetResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResource indicates an expected call of GetResource
func (_mr *MockResourcesClientMockRecorder) GetResource(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0, arg1}, arg2...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetResource", reflect.TypeOf((*MockResourcesClient)(nil).GetResource), _s...)
}

// ListResources mocks base method
func (_m *MockResourcesClient) ListResources(_param0 context.Context, _param1 *api.ListResourcesRequest, _param2 ...grpc.CallOption) (*api.ListResourcesResponse, error) {
	_s := []interface{}{_param0, _param1}
	for _, _x := range _param2 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "ListResources", _s...)
	ret0, _ := ret[0].(*api.ListResourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResources indicates an expected call of ListResources
func (_mr *MockResourcesClientMockRecorder) ListResources(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0, arg1}, arg2...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ListResources", reflect.TypeOf((*MockResourcesClient)(nil).ListResources), _s...)
}

// RemoveResource mocks base method
func (_m *MockResourcesClient) RemoveResource(_param0 context.Context, _param1 *api.RemoveResourceRequest, _param2 ...grpc.CallOption) (*api.RemoveResourceResponse, error) {
	_s := []interface{}{_param0, _param1}
	for _, _x := range _param2 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "RemoveResource", _s...)
	ret0, _ := ret[0].(*api.RemoveResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveResource indicates an expected call of RemoveResource
func (_mr *MockResourcesClientMockRecorder) RemoveResource(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0, arg1}, arg2...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "RemoveResource", reflect.TypeOf((*MockResourcesClient)(nil).RemoveResource), _s...)
}

// UpdateResource mocks base method
func (_m *MockResourcesClient) UpdateResource(_param0 context.Context, _param1 *api.UpdateResourceRequest, _param2 ...grpc.CallOption) (*api.UpdateResourceResponse, error) {
	_s := []interface{}{_param0, _param1}
	for _, _x := range _param2 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "UpdateResource", _s...)
	ret0, _ := ret[0].(*api.UpdateResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResource indicates an expected call of UpdateResource
func (_mr *MockResourcesClientMockRecorder) UpdateResource(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0, arg1}, arg2...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UpdateResource", reflect.TypeOf((*MockResourcesClient)(nil).UpdateResource), _s...)
}
